### ISSUE TITLE
Cannot load library: reloc_library

### ISSUE THREAD

**Issue by inflexible-simple** [frostwire/frostwire-jlibtorrent#155]
hi,
    There is a crash happen.
the device CPU info is :

     {"CPU ABI": "armeabi-v7a", "CPU ARCH BIT": "32", "CPU": ["arm", "v7", "neon"]}

crash message:

    java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1311]:   142 cannot locate 'pread64'...
                                                               at java.lang.Runtime.loadLibrary(Runtime.java:434)
                                                               at java.lang.System.loadLibrary(System.java:554)
                                                               at com.frostwire.jlibtorrent.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:17)
                                                               at com.frostwire.jlibtorrent.swig.byte_vector.<init>(byte_vector.java:39)
                                                               at com.frostwire.jlibtorrent.Vectors.bytes2byte_vector(Vectors.java:37)
                                                               at com.frostwire.jlibtorrent.TorrentInfo.bdecode0(TorrentInfo.java:652)
                                                               at com.frostwire.jlibtorrent.TorrentInfo.bdecode0(TorrentInfo.java:645)
                                                               at com.frostwire.jlibtorrent.TorrentInfo.<init>(TorrentInfo.java:34)

**Comment by inflexible-simple** [comment]
device android version is: 2.3.5

**Comment by aldenml** [comment]
what version if `jlibtorrent` is this?

**Comment by aldenml** [comment]
the minimum android version supported is 4.1 (Jelly Bean, API 16)
