### ISSUE TITLE
java.lang.LinkageError: Look for your architecture binary instructions at: https://github.com/frostwire/frostwire-jlibtorrent

### ISSUE THREAD

**Issue by khalledalkarmi** [frostwire/frostwire-jlibtorrent#163]
i have this problem how can if fix it ??
`Exception in thread "main" java.lang.LinkageError: Look for your architecture binary instructions at: https://github.com/frostwire/frostwire-jlibtorrent
	at com.frostwire.jlibtorrent.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:22)
	at com.frostwire.jlibtorrent.swig.libtorrent.version(libtorrent.java:29)
	at com.frostwire.jlibtorrent.LibTorrent.version(LibTorrent.java:33)
	at jbutton.Main.main(Main.java:19)
Caused by: java.lang.UnsatisfiedLinkError: no jlibtorrent in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.frostwire.jlibtorrent.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:17)
	... 3 more
`

**Comment by aldenml** [comment]
Hi, you need to provide the path to the native libraries to the JVM with `-Djava.library.path=`. The native libraries are inside the jars `jlibtorrent-windows` (or compatible architecture, see http://search.maven.org/#search%7Cga%7C1%7Cjlibtorrent). Just download the jar, uncompress it and put the shared library in the configured path.
