### ISSUE TITLE
[Android][1.2.0.10][Crash] RuntimeException: Invalid argument at fetchMagnet()

### ISSUE THREAD

**Issue by proninyaroslav** [frostwire/frostwire-jlibtorrent#172]
Hello. This happens only in Android 4.1 version (maybe and below versions) during fetching all magnet links (tested in x86 emulator). 
Stack trace:
```
   java.lang.RuntimeException: Invalid argument
   at com.frostwire.jlibtorrent.swig.libtorrent_jni.session_handle_add_torrent(Native Method)
   at com.frostwire.jlibtorrent.swig.session_handle.add_torrent(session_handle.java:99)
   at com.frostwire.jlibtorrent.SessionManager.fetchMagnet(SessionManager.java:614)
   at com.frostwire.jlibtorrent.SessionManager.fetchMagnet(SessionManager.java:645)
   at org.proninyaroslav.libretorrent.fragments.AddTorrentFragment$TorrentDecodeTask.doInBackground(AddTorrentFragment.java:516)
   at org.proninyaroslav.libretorrent.fragments.AddTorrentFragment$TorrentDecodeTask.doInBackground(AddTorrentFragment.java:483)
   at android.os.AsyncTask$2.call(AsyncTask.java:287)
   at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
   at java.util.concurrent.FutureTask.run(FutureTask.java:137)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
   at java.lang.Thread.run(Thread.java:856)
```

**Comment by aldenml** [comment]
Thanks for reporting, I will take a look at it

**Comment by aldenml** [comment]
Is this happening with any magnet, or one in particular?

**Comment by proninyaroslav** [comment]
Yes, with any magnet.

**Comment by aldenml** [comment]
Can you confirm this is still happening with `1.2.0.14`?

**Comment by aldenml** [comment]
I will close this, but only because we are dropping support for Android 4.1

**Comment by proninyaroslav** [comment]
Will the new versions of library work for Android 4.1?

**Comment by aldenml** [comment]
I will just continue to compile it with API 16 (Android 4.1) out of convenience.
