### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by e4basil** [frostwire/frostwire-jlibtorrent#192]
```
ANDROID_VERSION=6.0.1
APP_VERSION_NAME=1.5
BRAND=Xiaomi
PHONE_MODEL=Redmi Note 3
CUSTOM_DATA=
STACK_TRACE=java.lang.NoSuchMethodError: no static method "Lcom/frostwire/jlibtorrent/swig/libtorrent_jni;.SwigDirector_alert_notify_callback_on_alert(Lcom/frostwire/jlibtorrent/swig/alert_notify_callback;)V"
at com.frostwire.jlibtorrent.swig.libtorrent_jni.swig_module_init(Native Method)
at com.frostwire.jlibtorrent.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:3145)
at com.frostwire.jlibtorrent.swig.libtorrent_jni.alert_error_notification_get(Native Method)
at com.frostwire.jlibtorrent.swig.e.<clinit>(alert.java:493)
at com.frostwire.jlibtorrent.a.d.<clinit>(AlertType.java:11)
at com.frostwire.jlibtorrent.q.<clinit>(SessionManager.java:23)
at org.proninyaroslav.libretorrent.services.TorrentTaskService.onCreate(TorrentTaskService.java:217)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2910)
at android.app.ActivityThread.access$2000(ActivityThread.java:153)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1458)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:5527)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
```

**Comment by aldenml** [comment]
Hi @e4basil, I notice that you are using another project (`org.proninyaroslav.libretorrent`), this looks like a missing dependency, can you post your gradle dependencies?

**Comment by proninyaroslav** [comment]
This happened when it enabled option `minifyEnabled`, please see https://github.com/proninyaroslav/libretorrent/issues/157.

**Comment by aldenml** [comment]
right, well, this goes to the core of how JNI and `SWIG` works together, but it's very easy to solve. You just need to be sure to keep all the native methods declaration. Since they are all native, stripping them gains nothing (or very little) to you, all the actual code still remains in the native library. Modify your proguard rules files with the following line:
```
-keep class com.frostwire.jlibtorrent.swig.libtorrent_jni {*;}
```
you can use the configuration just to minify, take a look at: https://github.com/frostwire/frostwire/blob/master/android/build.gradle#L142

**Comment by abbasshah17** [comment]
Why is this issue closed? It is still there.

Using the latest library version: 1.2.7.0

I've added the following rule (also tried a few other variations)

    -keep class com.frostwire.jlibtorrent.swig.libtorrent_jni {*;}

You can confirm this error in the following sample app I've created [this repo](https://github.com/abbasshah17/frostwire-proguard-error-sample) just for this issue.

**Comment by gubatron** [comment]
I can't replicate

**Comment by gubatron** [comment]
try
`classpath 'com.android.tools.build:gradle:3.6.3'`

**Comment by abbasshah17** [comment]
> I can't replicate

Did you try the sample project I attached?

> ` classpath 'com.android.tools.build:gradle:3.6.3'`

Tried changing in the sample, still the same issue... Can you share the ndk version you are using?

**Comment by gubatron** [comment]
You can see them on the .travis.yml

    - env: os_build=android os_arch=arm android_api=19
    - env: os_build=android os_arch=arm64 android_api=21
    - env: os_build=android os_arch=x86 android_api=19
    - env: os_build=android os_arch=x86_64 android_api=21

https://dl.google.com/android/repository/android-ndk-r21-linux-x86_64.zip

**Comment by abbasshah17** [comment]
Finally found a rule that works...

    -keep public class com.frostwire.jlibtorrent.swig.** {
      *;
    }

There is some issue with R8 minifier, the keep rule mentioned in the README or in this thread doesn't work, haven't verified whether it's just the R8 or also proguard or something else. Also haven't verified if this works in proguard.

Strangely the rule only applies when added in app's `proguard-rules.pro`.
