### ISSUE TITLE
Crashing...

### ISSUE THREAD

**Issue by NandanDesai** [frostwire/frostwire-jlibtorrent#200]
I think this issue might have already brought up multiple times in the past and I tried to look up but couldn't really understand why the code is crashing.

Here's what's happening.

```
Exception in thread "main" java.lang.LinkageError: Look for your architecture binary instructions at: https://github.com/frostwire/frostwire-jlibtorrent
	at com.frostwire.jlibtorrent.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:33)
	at com.frostwire.jlibtorrent.swig.libtorrent.version(libtorrent.java:29)
	at com.frostwire.jlibtorrent.LibTorrent.version(LibTorrent.java:34)
	at controller.Torrentdownloader.main(Torrentdownloader.java:22)
Caused by: java.lang.UnsatisfiedLinkError: no jlibtorrent in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2654)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:876)
	at java.base/java.lang.System.loadLibrary(System.java:1875)
	at com.frostwire.jlibtorrent.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:27)
	... 3 more
```

Do I need to manually include the libtorrent binaries? If so, where can I find them. I'm running x64 Linux system.

What's going on here?

**Comment by aldenml** [comment]
Yes, you need to provide the binaries manually, you can get it for linux here https://search.maven.org/#search%7Cga%7C1%7Cjlibtorrent-linux, download the jar, uncompress it, locate the binary for your architecture, and put it in a place that the java runtime can find it. You need some familiarity with JNI.
