### ISSUE TITLE
I can't download it with the latest version. Can you help me see why?

### ISSUE THREAD

**Issue by XiongKe94** [frostwire/frostwire-jlibtorrent#262]
**Equipment**

Latest version: 1.2.14.1

Old version: 1.2.11.0

Android 11 devices

 
**Log**
2021-09-24 11:16:23.924 18261-18359/log-->i: ADD_TORRENT  added torrent: xxx_abc.com.XAPK
2021-09-24 11:16:23.931 18261-18359/log-->i: TORRENT_RESUMED  xxx_abc.com.XAPK resumed
2021-09-24 11:16:24.907 18261-18359/log-->i: STATS  xxx_abc.com.XAPK: [1904] 0 0 0 0 0 0
2021-09-24 11:16:24.918 18261-18359/log-->i: STATE_CHANGED  xxx_abc.com.XAPK: state changed to: downloading
2021-09-24 11:16:24.918 18261-18359/log-->i: TORRENT_CHECKED  xxx_abc.com.XAPK checked
2021-09-24 11:16:24.919 18261-18359/log-->i: TRACKER_ANNOUNCE  xxx_abc.com.XAPK (xhttps://xxxxx?k=xx)[198.18.133.151:42967] sending announce (started)
2021-09-24 11:16:24.919 18261-18359/log-->i: TRACKER_ANNOUNCE  xxx_abc.com.XAPK (xhttps://xxxxx?k=xx)[192.168.9.184:43481] sending announce (started)
2021-09-24 11:16:24.919 18261-18359/log-->i: TRACKER_ANNOUNCE  xxx_abc.com.XAPK (xhttps://xxxxx?k=xx)[127.0.0.1:39969] sending announce (started)
2021-09-24 11:16:24.920 18261-18359/log-->i: TRACKER_ANNOUNCE  xxx_abc.com.XAPK (xhttps://xxxxx?k=xx)[[fe80::2e1:ac7:89bb:ce31%tun0]:40383] sending announce (started)
2021-09-24 11:16:24.920 18261-18359/log-->i: TRACKER_ANNOUNCE  xxx_abc.com.XAPK (xhttps://xxxxx?k=xx)[[fe80::8c9c:b7ff:fe9b:99e1%wlan0]:37387] sending announce (started)
2021-09-24 11:16:24.920 18261-18359/log-->i: TRACKER_ANNOUNCE  xxx_abc.com.XAPK (xhttps://xxxxx?k=xx)[[fe80::55b0:cac5:d3e5:3b48%r_rmnet_data0]:41873] sending announce (started)
2021-09-24 11:16:24.921 18261-18359/log-->i: TRACKER_ANNOUNCE  xxx_abc.com.XAPK (xhttps://xxxxx?k=xx)[[fe80::b388:f4d4:e2ad:6052%rmnet_data0]:40551] sending announce (started)
2021-09-24 11:16:24.921 18261-18359/log-->i: TRACKER_ANNOUNCE  xxx_abc.com.XAPK (xhttps://xxxxx?k=xx)[[fe80::1085:8ff:fef3:c470%dummy0]:41481] sending announce (started)
2021-09-24 11:16:24.921 18261-18359/log-->i: TRACKER_ANNOUNCE  xxx_abc.com.XAPK (xhttps://xxxxx?k=xx)[[::1]:39641] sending announce (started)
2021-09-24 11:16:24.922 18261-18359/log-->i: LSD_PEER  xxx_abc.com.XAPK peer [ [fe80::1085:8ff:fef3:c470%dummy0]:42967 client: Unknown ]: received peer from local service discovery
2021-09-24 11:16:24.922 18261-18359/log-->i: PEER_CONNECT  xxx_abc.com.XAPK peer [ 193.70.47.70:443 client: Unknown ] connecting to peer (SSL/TCP)
2021-09-24 11:16:24.922 18261-18359/log-->i: TRACKER_ERROR  xxx_abc.com.XAPK (xhttps://xxxxx?k=xx)[[::1]:39641] skipping tracker announce (unreachable) "" (1)
2021-09-24 11:16:24.923 18261-18359/log-->i: TRACKER_ERROR  xxx_abc.com.XAPK (xhttps://xxxxx?k=xx)[[fe80::1085:8ff:fef3:c470%dummy0]:41481] skipping tracker announce (unreachable) "" (1)
2021-09-24 11:16:24.923 18261-18359/log-->i: TRACKER_ERROR  xxx_abc.com.XAPK (xhttps://xxxxx?k=xx)[[fe80::b388:f4d4:e2ad:6052%rmnet_data0]:40551] skipping tracker announce (unreachable) "" (1)
2021-09-24 11:16:24.923 18261-18359/log-->i: TRACKER_ERROR  xxx_abc.com.XAPK (xhttps://xxxxx?k=xx)[[fe80::55b0:cac5:d3e5:3b48%r_rmnet_data0]:41873] skipping tracker announce (unreachable) "" (1)
2021-09-24 11:16:24.923 18261-18359/log-->i: TRACKER_ERROR  xxx_abc.com.XAPK (xhttps://xxxxx?k=xx)[[fe80::8c9c:b7ff:fe9b:99e1%wlan0]:37387] skipping tracker announce (unreachable) "" (1)
2021-09-24 11:16:24.924 18261-18359/log-->i: TRACKER_ERROR  xxx_abc.com.XAPK (xhttps://xxxxx?k=xx)[[fe80::2e1:ac7:89bb:ce31%tun0]:40383] skipping tracker announce (unreachable) "" (1)
2021-09-24 11:16:24.924 18261-18359/log-->i: TRACKER_ERROR  xxx_abc.com.XAPK (xhttps://xxxxx?k=xx)[127.0.0.1:39969] skipping tracker announce (unreachable) "" (1)
2021-09-24 11:16:24.924 18261-18359/log-->i: LSD_PEER  xxx_abc.com.XAPK peer [ [fe80::1085:8ff:fef3:c470%dummy0]:42967 client: Unknown ]: received peer from local service discovery
2021-09-24 11:16:24.925 18261-18359/log-->i: LSD_PEER  xxx_abc.com.XAPK peer [ [fe80::1085:8ff:fef3:c470%dummy0]:42967 client: Unknown ]: received peer from local service discovery
2021-09-24 11:16:25.872 18261-18359/log-->i: PEER_DISCONNECTED  xxx_abc.com.XAPK peer [ 193.70.47.70:443 client: Unknown ] disconnecting (SSL/TCP) [connect] [asio.ssl]: asio.ssl error (reason: 0)
2021-09-24 11:16:25.906 18261-18359/log-->i: STATS  xxx_abc.com.XAPK: [1000] 0 0 0 0 40 0
2021-09-24 11:16:26.116 18261-18359/log-->i: TRACKER_ERROR  xxx_abc.com.XAPK (xhttps://xxxxx?k=xx)[192.168.9.184:43481] unspecified system error "" (1)
2021-09-24 11:16:26.907 18261-18359/log-->i: STATS  xxx_abc.com.XAPK: [1000] 0 0 0 0 0 0
2021-09-24 11:16:26.914 18261-18359/log-->i: LSD_PEER  xxx_abc.com.XAPK peer [ [fe80::1085:8ff:fef3:c470%dummy0]:42967 client: Unknown ]: received peer from local service discovery
2021-09-24 11:16:26.917 18261-18359/log-->i: LSD_PEER  xxx_abc.com.XAPK peer [ [fe80::1085:8ff:fef3:c470%dummy0]:42967 client: Unknown ]: received peer from local service discovery
2021-09-24 11:16:27.907 18261-18359/log-->i: STATS  xxx_abc.com.XAPK: [1000] 0 0 0 0 0 0
2021-09-24 11:16:28.908 18261-18359/log-->i: STATS  xxx_abc.com.XAPK: [1000] 0 0 0 0 0 0
2021-09-24 11:16:29.908 18261-18359/log-->i: STATS  xxx_abc.com.XAPK: [1000] 0 0 0 0 0 0
2021-09-24 11:16:30.909 18261-18359/log-->i: STATS  xxx_abc.com.XAPK: [1000] 0 0 0 0 0 0
2021-09-24 11:16:30.917 18261-18359/log-->i: LSD_PEER  xxx_abc.com.XAPK peer [ [fe80::1085:8ff:fef3:c470%dummy0]:42967 client: Unknown ]: received peer from local service discovery
2021-09-24 11:16:30.921 18261-18359/log-->i: LSD_PEER  xxx_abc.com.XAPK peer [ [fe80::1085:8ff:fef3:c470%dummy0]:42967 client: Unknown ]: received peer from local service discovery
2021-09-24 11:16:31.910 18261-18359/log-->i: STATS  xxx_abc.com.XAPK: [1000] 0 0 0 0 0 0
2021-09-24 11:16:32.910 18261-18359/log-->i: STATS  xxx_abc.com.XAPK: [1000] 0 0 0 0 0 0

**Comment by gubatron** [comment]
did you build the library or you used the pre-built binaries?
https://github.com/frostwire/frostwire-jlibtorrent/releases/tag/release%2F1.2.14.1

**Comment by XiongKe94** [comment]
I am using a compiled so file。

**Comment by XiongKe94** [comment]
@gubatron

**Comment by gubatron** [comment]
does this happen with all .torrents and all android 11 devices you test?
I can't replicate on my end

**Comment by XiongKe94** [comment]
@gubatron  Unable to load so

2021-11-17 18:29:35.261 22431-22431/com.xxxx.demo I/System.out: Trying jlibtorrent.<so|dylib>...
2021-11-17 18:29:35.263 22431-22431/com.xxxx.demo W/System.err: java.lang.UnsatisfiedLinkError: dlopen failed: library "libjlibtorrent.so" not found
2021-11-17 18:29:35.263 22431-22431/com.xxxx.demo W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
2021-11-17 18:29:35.263 22431-22431/com.xxxx.demo W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
2021-11-17 18:29:35.263 22431-22431/com.xxxx.demo W/System.err:     at java.lang.System.loadLibrary(System.java:1664)
2021-11-17 18:29:35.263 22431-22431/com.xxxx.demo W/System.err:     at com.frostwire.jlibtorrent.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:25)
2021-11-17 18:29:35.263 22431-22431/com.xxxx.demo W/System.err:     at com.frostwire.jlibtorrent.swig.libtorrent_jni.new_settings_pack__SWIG_0(Native Method)
2021-11-17 18:29:35.263 22431-22431/com.xxxx.demo W/System.err:     at com.frostwire.jlibtorrent.swig.settings_pack.<init>(settings_pack.java:40)
2021-11-17 18:29:35.263 22431-22431/com.xxxx.demo W/System.err:     at com.apkmatrix.components.ultradownloader.torrentstream.TorrentUtils.defaultSettingsPack(TorrentUtils.kt:175)
2021-11-17 18:29:35.263 22431-22431/com.xxxx.demo W/System.err:     at com.apkmatrix.components.ultradownloader.torrentstream.TorrentUtils.newSessionManager(TorrentUtils.kt:161)
2021-11-17 18:29:35.263 22431-22431/com.xxxx.demo W/System.err:     at com.apkmatrix.components.ultradownloader.torrentstream.TorrentStream$startDownload$1.invokeSuspend(TorrentStream.kt:85)
2021-11-17 18:29:35.263 22431-22431/com.xxxx.demo W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2021-11-17 18:29:35.263 22431-22431/com.xxxx.demo W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2021-11-17 18:29:35.263 22431-22431/com.xxxx.demo W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
2021-11-17 18:29:35.263 22431-22431/com.xxxx.demo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2021-11-17 18:29:35.263 22431-22431/com.xxxx.demo W/System.err:     at android.os.Looper.loop(Looper.java:223)
2021-11-17 18:29:35.263 22431-22431/com.xxxx.demo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7664)
2021-11-17 18:29:35.263 22431-22431/com.xxxx.demo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-11-17 18:29:35.263 22431-22431/com.xxxx.demo W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
2021-11-17 18:29:35.263 22431-22431/com.xxxx.demo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-11-17 18:29:35.266 22431-22431/com.xxxx.demo I/System.out: Loaded jlibtorrent-1.2.14.2
