### ISSUE TITLE
No implementation found for void com.frostwire.jlibtorrent.swig.libtorrent_jni.swig_module_init()

### ISSUE THREAD

**Issue by mianharisali** [frostwire/frostwire-jlibtorrent#268]
Jlibtorrent version = 1.2.15.1
Android version =  4 , 5 , 6
1 device from crash list = Brand:Xiaomi  , Model:Redmi 4 Pro

```
Fatal Exception: java.lang.UnsatisfiedLinkError: No implementation found for void com.frostwire.jlibtorrent.swig.libtorrent_jni.swig_module_init() (tried Java_com_frostwire_jlibtorrent_swig_libtorrent_1jni_swig_1module_1init and Java_com_frostwire_jlibtorrent_swig_libtorrent_1jni_swig_1module_1init__)
       at com.frostwire.jlibtorrent.swig.libtorrent_jni.swig_module_init(libtorrent_jni.java)
       at com.frostwire.jlibtorrent.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:3252)
       at com.frostwire.jlibtorrent.swig.byte_vector.<init>(byte_vector.java:40)
       at com.frostwire.jlibtorrent.Vectors.bytes2byte_vector(Vectors.java:38)
       at com.frostwire.jlibtorrent.TorrentInfo.bdecode0(TorrentInfo.java:679)
       at com.frostwire.jlibtorrent.TorrentInfo.bdecode(TorrentInfo.java:654)
```

**Comment by gubatron** [comment]
minSdkVersion 24 (Android 7.0)

You need Android 7, older versions are no longer supported.
