### ISSUE TITLE
jLibtorrent on Android 11 - Fatal Exception in AlertListener, v2

### ISSUE THREAD

**Issue by pvishnyakov** [frostwire/frostwire-jlibtorrent#300]
Hi.

Replaced 1.2.19.0 with latest v2 files available, now getting this error:
````
FATAL EXCEPTION: SessionManager-alertsLoop
                 Process: org.djche.tormund, PID: 12553
                 java.lang.NullPointerException: Attempt to invoke interface method 'com.frostwire.jlibtorrent.alerts.Alert com.frostwire.jlibtorrent.alerts.Alerts$CastLambda.cast(com.frostwire.jlibtorrent.swig.alert)' on a null object reference
                 	at com.frostwire.jlibtorrent.alerts.Alerts.cast(Alerts.java:22)
                 	at com.frostwire.jlibtorrent.SessionManager$5.run(SessionManager.java:1199)
                 	at java.lang.Thread.run(Thread.java:923)
````

Most interesting - error appears when app is running normally. If the app is running in debug mode and beakpoints are set inside AlertListener (on each alert) - step-by-step execution is allowing to bypass the issue and no error arise.

AlertListener code:
````
			alertListener = new AlertListener() {
				
				@Override
				public int[] types() {
					return null;
				}
				
				@Override
				public void alert(Alert<?> alert) {
					AlertType type = alert.type();
					switch (type) {
						case ADD_TORRENT:
							try {
								AddTorrentAlert ata = (AddTorrentAlert) alert;
								log("Torrent added");
								ata.handle().pause();
								initPriorities(ata.handle(), selectedFileIndex, false);
								ata.handle().resume();
								streaming.set(true);
							} catch (Exception e) {
								log("add torrent error", e);
							}
							break;
					}
				}
			};
````

Further investigation revealed that error occurs only when initPriorities is called but no error inside initPriorities itself.
Seems that something is causing error after execution returned from initPriorities back to AlertListener.

Here is the code of initPriorities:
````
	private void initPriorities(TorrentHandle torrentHandle, int selectedFileIndex, boolean forceInit) {
		log("Initializing priorities...");
		
		torrentHandle.setFlags(TorrentFlags.SEQUENTIAL_DOWNLOAD);
		
		// piece priorities
		Priority[] piecePriorities = torrentHandle.piecePriorities();
		Arrays.fill(piecePriorities, Priority.IGNORE);
		torrentHandle.clearPieceDeadlines();
		torrentHandle.prioritizePieces(piecePriorities);
		
		// file priorities
		Priority[] filePriorities = torrentHandle.filePriorities();
		Arrays.fill(filePriorities, Priority.IGNORE);
		filePriorities[selectedFileIndex] = Priority.NORMAL;
		torrentHandle.prioritizeFiles(filePriorities);
		
		for (int i = 0; i < piecesInFile; i++) {
			final int curIdx = firstFilePiece + i;
			if (i < criticalStartPieces) {
				torrentHandle.piecePriority(curIdx, Priority.SEVEN);
				torrentHandle.setPieceDeadline(curIdx, 1000);
			} else {
				if (i >= piecesInFile - criticalEndPieces) {
					torrentHandle.piecePriority(curIdx, Priority.SEVEN);
					torrentHandle.setPieceDeadline(curIdx, 1000);
				} else {
					torrentHandle.piecePriority(curIdx, Priority.IGNORE);
//					torrentHandle.setPieceDeadline(curIdx, 2000 + i * 100);
				}
			}
		}
		log("Priorities initialized");
	}
````

What may be a problem?

**Comment by pvishnyakov** [comment]
Returned back 1.2.19.0 jars, didn’t change anything else, all works again

**Comment by gubatron** [comment]
You will have to do a lot of refactors to upgrade to libtorrent 2.0, a lot of the API changed.
I'd take a look at the jlibtorrent examples and tests.

**Comment by pvishnyakov** [comment]
I have checked demos of course. Most of changes happened in APIs I never deal with so there’s not much to refactor. 
What may cause the behavior when everything works in debugger mode step by step execution but fails when running normally?
