### ISSUE TITLE
Strange QueuedThreadPool exception, UnknownError: Success

### ISSUE THREAD

**Issue by tchoulihan** [frostwire/frostwire-jlibtorrent#31]
I occasionally get a strange exception when I run:
```java
TorrentHandle torrent = session.addTorrent(torrentFile, outputParent);
```

What could be causing it?
```java
21:04:35.293 [qtp790420105-37] WARN  o.e.j.util.thread.QueuedThreadPool - 
java.lang.UnknownError: Success
	at com.frostwire.jlibtorrent.swig.libtorrent_jni.new_torrent_info__SWIG_3(Native Method) ~[torrenttunes-server.jar:na]
	at com.frostwire.jlibtorrent.swig.torrent_info.<init>(torrent_info.java:51) ~[torrenttunes-server.jar:na]
	at com.frostwire.jlibtorrent.TorrentInfo.<init>(TorrentInfo.java:32) ~[torrenttunes-server.jar:na]
	at com.frostwire.jlibtorrent.Session.addTorrent(Session.java:160) ~[torrenttunes-server.jar:na]
	at com.frostwire.jlibtorrent.Session.addTorrent(Session.java:191) ~[torrenttunes-server.jar:na]
	at com.torrenttunes.client.LibtorrentEngine.addTorrent(LibtorrentEngine.java:182) ~[torrenttunes-server.jar:na]
```

**Comment by aldenml** [comment]
Is this error with one particular torrent file? We don't use that method but in a very critical point, our software update process (CC @gubatron).

Can you create some sort of replication scenario?

**Comment by tchoulihan** [comment]
No, its happening to a lot of torrents, as I add them. Let me try to think of a way to replicate it.

**Comment by gubatron** [comment]
think it might be one of those errors caused by early GC?

**Comment by aldenml** [comment]
Yes, but I need to research more about it.

**Comment by tchoulihan** [comment]
It looks like this is the same issue:
https://github.com/frostwire/frostwire-android/issues/221

**Comment by aldenml** [comment]
Are you using an up to date copy of our source code?

**Comment by gubatron** [comment]
OT: Does the search on torrenttunes work?
Last night I built the server and the client, but search wasn't working for me.

**Comment by tchoulihan** [comment]
@aldenml , I'm pretty sure so, new as of maybe 3 weeks ago.

@gubatron Sorry about that, this is still in alpha version.

**Comment by aldenml** [comment]
@tchoulihan Did you close it for any particular reason?

**Comment by tchoulihan** [comment]
I stopped getting the error for some reason. Maybe I did something to free
up more threads, but I stopped getting it.
