### ISSUE TITLE
MillionTorrentTester

### ISSUE THREAD

**Issue by tchoulihan** [frostwire/frostwire-jlibtorrent#34]
@aldenml I've worked up the torrent tester example. I'm not sure a pull request would be the best way to give it to you, so I'll just put the code for the class here.

I'd highly suggest also adding the createAndSaveTorrent(or portions of it) into jlibtorrent, because its very useful.

Apologies in advance for the verbose amount of listeners, but IMO its better than the tick.
```java
package com.torrenttunes.client.tools;

import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.URI;
import java.util.Map;

import com.frostwire.jlibtorrent.Entry;
import com.frostwire.jlibtorrent.Session;
import com.frostwire.jlibtorrent.SessionSettings;
import com.frostwire.jlibtorrent.TorrentAlertAdapter;
import com.frostwire.jlibtorrent.TorrentHandle;
import com.frostwire.jlibtorrent.alerts.AddTorrentAlert;
import com.frostwire.jlibtorrent.alerts.BlockDownloadingAlert;
import com.frostwire.jlibtorrent.alerts.BlockFinishedAlert;
import com.frostwire.jlibtorrent.alerts.BlockTimeoutAlert;
import com.frostwire.jlibtorrent.alerts.DhtReplyAlert;
import com.frostwire.jlibtorrent.alerts.FastresumeRejectedAlert;
import com.frostwire.jlibtorrent.alerts.FileErrorAlert;
import com.frostwire.jlibtorrent.alerts.HashFailedAlert;
import com.frostwire.jlibtorrent.alerts.PeerBanAlert;
import com.frostwire.jlibtorrent.alerts.PeerBlockedAlert;
import com.frostwire.jlibtorrent.alerts.PeerConnectAlert;
import com.frostwire.jlibtorrent.alerts.PeerDisconnectedAlert;
import com.frostwire.jlibtorrent.alerts.PeerErrorAlert;
import com.frostwire.jlibtorrent.alerts.PeerSnubbedAlert;
import com.frostwire.jlibtorrent.alerts.PeerUnsnubbedAlert;
import com.frostwire.jlibtorrent.alerts.PerformanceAlert;
import com.frostwire.jlibtorrent.alerts.RequestDroppedAlert;
import com.frostwire.jlibtorrent.alerts.SaveResumeDataAlert;
import com.frostwire.jlibtorrent.alerts.SaveResumeDataFailedAlert;
import com.frostwire.jlibtorrent.alerts.ScrapeFailedAlert;
import com.frostwire.jlibtorrent.alerts.ScrapeReplyAlert;
import com.frostwire.jlibtorrent.alerts.StateChangedAlert;
import com.frostwire.jlibtorrent.alerts.TorrentAddedAlert;
import com.frostwire.jlibtorrent.alerts.TorrentCheckedAlert;
import com.frostwire.jlibtorrent.alerts.TorrentDeleteFailedAlert;
import com.frostwire.jlibtorrent.alerts.TorrentDeletedAlert;
import com.frostwire.jlibtorrent.alerts.TorrentErrorAlert;
import com.frostwire.jlibtorrent.alerts.TorrentFinishedAlert;
import com.frostwire.jlibtorrent.alerts.TorrentPausedAlert;
import com.frostwire.jlibtorrent.alerts.TorrentPrioritizeAlert;
import com.frostwire.jlibtorrent.alerts.TorrentRemovedAlert;
import com.frostwire.jlibtorrent.alerts.TorrentResumedAlert;
import com.frostwire.jlibtorrent.alerts.TorrentUpdateAlert;
import com.frostwire.jlibtorrent.alerts.TrackerAnnounceAlert;
import com.frostwire.jlibtorrent.alerts.TrackerErrorAlert;
import com.frostwire.jlibtorrent.alerts.TrackerReplyAlert;
import com.frostwire.jlibtorrent.alerts.TrackerWarningAlert;
import com.frostwire.jlibtorrent.alerts.UnwantedBlockAlert;
import com.frostwire.jlibtorrent.swig.create_torrent;
import com.frostwire.jlibtorrent.swig.error_code;
import com.frostwire.jlibtorrent.swig.file_storage;
import com.frostwire.jlibtorrent.swig.libtorrent;
import com.google.common.io.Files;

//java -cp target/torrenttunes-client.jar com.torrenttunes.client.tools.MillionTorrentTester
public class MillionTorrentTester {

	public static void main(String[] args) throws IOException {
		
		Session session = new Session();
		SessionSettings sessionSettings = SessionSettings.newDefaults();
		
		sessionSettings.setActiveDownloads(10);
		sessionSettings.setActiveLimit(999999);
		sessionSettings.setActiveSeeds(999999);
		sessionSettings.setActiveTrackerLimit(999999);
		session.stopLSD();
		session.stopDHT();
		
		
		session.setSettings(sessionSettings);
		
		
		for (int i = 0; i < 10000; i++) {
			System.out.println(i);
			File torrentFile = File.createTempFile("t_" + i + "_", ".torrent");
			File inputFileOrDir = File.createTempFile("f_" + i + "_", ".tmp");
			Files.write("1".getBytes(), inputFileOrDir);
			
			File tFile = createAndSaveTorrent(torrentFile, inputFileOrDir);
			
			TorrentHandle torrent = session.addTorrent(tFile, inputFileOrDir.getParentFile());
			
			torrent.setAutoManaged(false);
			torrent.resume();
			
			addListeners(session, torrent);
			
			System.out.println("Added file " + tFile.getAbsolutePath());
			
		}
		
        System.out.println("Press ENTER to exit");
        System.in.read();
        
	
	}
	
	private static File createAndSaveTorrent(File torrentFile, File inputFileOrDir) {

		file_storage fs = new file_storage();

		// Add the file
		libtorrent.add_files(fs, inputFileOrDir.getAbsolutePath());

		create_torrent t = new create_torrent(fs);


		// Add trackers in tiers
		for (URI announce : DataSources.ANNOUNCE_LIST()) {
			t.add_tracker(announce.toASCIIString());
		}


		t.set_priv(false);
		t.set_creator(System.getProperty("user.name"));

		error_code ec = new error_code();


		// reads the files and calculates the hashes
		libtorrent.set_piece_hashes(t, inputFileOrDir.getParent(), ec);

		if (ec.value() != 0) {
			System.out.println(ec.message());
		}

		// Get the bencode and write the file
		Entry entry =  new Entry(t.generate());

		Map<String, Entry> entryMap = entry.dictionary();
		Entry entryFromUpdatedMap = Entry.fromMap(entryMap);
		final byte[] bencode = entryFromUpdatedMap.bencode();

		try {
			FileOutputStream fos;

			fos = new FileOutputStream(torrentFile);

			BufferedOutputStream bos = new BufferedOutputStream(fos);
			bos.write(bencode);
			bos.flush();
			bos.close();
		} catch (IOException e) {
			System.err.println("Couldn't write file");
			e.printStackTrace();
		}

		return torrentFile;
	}
	
	private static void addListeners(Session session, TorrentHandle torrent) {
		// Add the listeners
				session.addListener(new TorrentAlertAdapter(torrent) {

					//			@Override
					//			public void stats(StatsAlert alert) {
					//				TorrentStats ts = TorrentStats.create(torrent);
					//				System.out.println(ts.toString());
					//
					//				super.stats(alert);
					//			}

					@Override
					public void stateChanged(StateChangedAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
					}
					
					@Override
					public void scrapeFailed(ScrapeFailedAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
					}
					

					@Override
					public void blockFinished(BlockFinishedAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
					}

					@Override
					public void torrentFinished(TorrentFinishedAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
						//				torrent.saveResumeData();
					}

					@Override
					public void blockDownloading(BlockDownloadingAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
					}

					@Override
					public void peerConnect(PeerConnectAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
					}
					@Override
					public void peerSnubbed(PeerSnubbedAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());

					}

					@Override
					public void peerUnsnubbe(PeerUnsnubbedAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
					}

					@Override
					public void requestDropped(RequestDroppedAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
					}

					@Override
					public void saveResumeData(SaveResumeDataAlert alert) {
//						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
//						Entry srdata = alert.getResumeData();
//						try {
//							String srDataPath = DataSources.TORRENTS_DIR() + "/srdata_" + torrent.getName();
//							Files.write(Paths.get(srDataPath), 
//									srdata.bencode());
//							System.out.println("Wrote save_resume_data: " + srDataPath);
//						} catch (IOException e) {
//							// TODO Auto-generated catch block
//							e.printStackTrace();
//						}



					}


					@Override
					public void saveResumeDataFailed(SaveResumeDataFailedAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
					}

					@Override
					public void peerDisconnected(PeerDisconnectedAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
					}

					@Override
					public void peerBan(PeerBanAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());

					}

					@Override
					public void peerError(PeerErrorAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());

					}

					@Override
					public void addTorrent(AddTorrentAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
					}

					@Override
					public void peerBlocked(PeerBlockedAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());

					}

					@Override
					public void trackerAnnounce(TrackerAnnounceAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());

					}

					@Override
					public void trackerReply(TrackerReplyAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
						//				torrent.setAutoManaged(false);
						//				torrent.pause();
						//				torrent.saveResumeData();
					}

					@Override
					public void trackerWarning(TrackerWarningAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());

					}

					@Override
					public void trackerError(TrackerErrorAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());

					}


					@Override
					public void dhtReply(DhtReplyAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
						//				torrent.setAutoManaged(true);
					}

					@Override
					public void torrentPaused(TorrentPausedAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());

//						torrent.saveResumeData();
						//				torrent.resume();
					}

					@Override
					public void torrentError(TorrentErrorAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
					}

					@Override
					public void torrentResumed(TorrentResumedAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
					}

					@Override
					public void torrentUpdate(TorrentUpdateAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
					}


					@Override
					public void torrentChecked(TorrentCheckedAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
					}

					@Override
					public void torrentRemoved(TorrentRemovedAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
					}

					@Override
					public void torrentAdded(TorrentAddedAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
					}

					@Override
					public void torrentDeleted(TorrentDeletedAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
					}

					@Override
					public void torrentDeleteFailed(TorrentDeleteFailedAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());

					}


					@Override
					public void fastresumeRejected(FastresumeRejectedAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
					}

					@Override
					public void blockTimeout(BlockTimeoutAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
					}

					@Override
					public void fileError(FileErrorAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
					}

					@Override
					public void hashFailed(HashFailedAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
					}

					@Override
					public void performance(PerformanceAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
					}

					@Override
					public void scrapeReply(ScrapeReplyAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
					}

					@Override
					public void torrentPrioritize(TorrentPrioritizeAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
					}

					@Override
					public void unwantedBlock(UnwantedBlockAlert alert) {
						System.out.println(alert.getType() + " - " + alert.getSwig().what() + " - " + alert.getSwig().message());
					}


				});



    
	}
}

```

**Comment by aldenml** [comment]
Hi @tchoulihan, I will take a look at this issue, it is something that is affecting our bittorrent client (FrostWire) with just a thousand torrents. I saw the other issues too.

First, I need to ask you if you are willing to use our master branch. It's up to date with libtorrent master and  we are currently in the process of publishing in maven central. The branch you are using is pretty much frozen. I'm willing to help with any api incompatibility.

The second question is about the environment, specially the OS, if you are in a cloud or local pc, CPU and memory available.

**Comment by tchoulihan** [comment]
@aldenml Okay, just pulled into a local branch of mine, and am using the newest one by just copying the folder and necessary binaries(Of course maven will be really nice once you guys get there).

I'm finding a lot of issues when updating. A bunch of methods for Session and SessionSettings are missing.

Using SettingsPack instead of SessionSettings, I'm missing the newDefaults(). I supposed just initializing it like : `SettingsPack sessionSettings = new SettingsPack();` will do the same.

`session.stopLSD()` and `session.stopDHT()` are gone.
`sessionSettings.setActiveLimit(...)` is gone.

And `session.setSettings` is shown as deprecated. How do I apply a settingsPack to my specific session? Or retrieve the settingsPack for my session?

I also highly recommend using builder pattern for things like `session.addTorrent(`, that have some required and some optional parameters. http://stackoverflow.com/questions/5007355/builder-pattern-in-effective-java . You could use this style for your settingspack, but its not really necessary considering all its parameters are optional.

**Comment by aldenml** [comment]
Thank you for your suggestion. Now I' working in a way to enable the TORRENT_DISK_STATS in the build but at the same time be able to disable at runtime.

**Comment by tchoulihan** [comment]
@aldenml 

No problem, thanks!

**Comment by aldenml** [comment]
@tchoulihan It's your repo (with the branch) public?

**Comment by tchoulihan** [comment]
Also, I'm getting this error when using the linux binary: 
```java
Exception in thread "main" java.lang.UnsatisfiedLinkError: Look for your architecture binary at: https://github.com/frostwire/frostwire-jlibtorrent/tree/master/binaries
	at com.frostwire.jlibtorrent.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:17)
	at com.frostwire.jlibtorrent.swig.libtorrentConstants.<clinit>(libtorrentConstants.java:12)
	at com.frostwire.jlibtorrent.Fingerprint.<init>(Fingerprint.java:22)
	at com.frostwire.jlibtorrent.Session.<init>(Session.java:104)
	at com.torrenttunes.client.tools.MillionTorrentTester.main(MillionTorrentTester.java:65)
```
I did copy the new binaries over too. 

> It's your repo (with the branch) public?
What do you mean? I pulled frostwire-jlibtorrent/master into a local branch that I haven't committed to public yet. Why don't you just create feature or development branches, then I can submit pull request changes to those if necessary, and the collaboration can happen on your repos.

**Comment by aldenml** [comment]
Ok, here it is: https://github.com/frostwire/frostwire-jlibtorrent/tree/million-torrents

Let's see how it goes.

**Comment by aldenml** [comment]
Are you developing in Linux? Are you able to run build-linux.sh (inside the swig folder)?

**Comment by tchoulihan** [comment]
@aldenml sorry about the binary error, I fixed it, see above.

**Comment by tchoulihan** [comment]
Okay I just issued a pull request: https://github.com/frostwire/frostwire-jlibtorrent/pull/35

**Comment by gubatron** [comment]
@tchoulihan 

To stop LSD, you basically have to change the setting, stop the libtorrent core, and start it again.

To stop DHT [this is how you can do it already](https://github.com/frostwire/frostwire-desktop/blob/master/src/com/limegroup/gnutella/gui/options/panes/TorrentConnectionPaneItem.java#L130).

**Comment by tchoulihan** [comment]
@gubatron I assume this will stop the DHT then:
```java
DHT dht = new DHT(session);
dht.stop();
```

Thanks sir.
