### ISSUE TITLE
Linux 32 bit issue... messages about stack_guard?

### ISSUE THREAD

**Issue by tchoulihan** [frostwire/frostwire-jlibtorrent#54]
Hey guys, someone running my client is getting the following error:

```
Java HotSpot(TM) Server VM warning: You have loaded library /home/troll/.torrenttunes-client/src/lib/x86_64/libjlibtorrent.so which might have disabled stack guard. The VM will try to fix the stack guard now.
    It's highly recommended that you fix the library with 'execstack -c ', or link it with '-z noexecstack'.
    Exception in thread "main" java.lang.UnsatisfiedLinkError: Look for your architecture binary instructions at:    https://github.com/frostwire/frostwire-jlibtorrent
```

Here's their full output, with java versions and uname:
```
    troll@troll ~ ls -l ~/.torrenttunes-client/src/lib/x86_64/libjlibtorrent.so
    -rw-r--r-- 1 troll troll 6323080 Eyl 14 20:00 /home/troll/.torrenttunes-client/src/lib/x86_64/libjlibtorrent.so

    troll@troll ~/Desktop java -version 
    java version "1.8.0_60"
    Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
    Java HotSpot(TM) Server VM (build 25.60-b23, mixed mode)

    troll@troll ~ uname -a    
    Linux troll 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:31:42 UTC 2014 i686 i686 i686 GNU/Linux

    troll@troll ~/Desktop java -jar torrenttunes-launcher.jar
    20:21:23.030 [main] INFO ROOT - Copying launcher jar to /home/troll/.torrenttunes-client/torrenttunes-launcher.jar ...
    20:21:23.068 [main] INFO ROOT - This jar: /home/troll/Desktop/torrenttunes-launcher.jar Launcher Jar: /home/troll/.torrenttunes-client/torrenttunes-launcher.jar
    20:21:23.126 [main] INFO com.torrenttunes.launcher.Updater - Checking for update...
    20:21:29.589 [main] INFO com.torrenttunes.launcher.Updater - Current Tag #: 0.5.0
    20:21:29.590 [main] INFO com.torrenttunes.launcher.Updater - Latest Tag #: 0.5.0
    20:21:29.591 [main] INFO com.torrenttunes.launcher.Updater - No updates found
    20:21:33.394 [main] INFO com.torrenttunes.client.tools.Tools - Home directory already exists
    20:21:33.487 [main] INFO com.torrenttunes.client.tools.Tools - The source directory already exists
    20:21:33.496 [main] INFO com.torrenttunes.client.tools.Tools - tools.js = /home/troll/.torrenttunes-client/src/web/js/tools.js
    20:21:33.639 [main] INFO c.t.client.db.InitializeTables - Using database located at : /home/troll/.torrenttunes-client/db/db.sqlite
    20:21:33.661 [main] INFO c.t.client.db.InitializeTables - DB already exists
    20:21:35.393 [main] INFO com.torrenttunes.client.db.Actions - Storage path = /home/troll/.torrenttunes-client/music
    20:21:35.395 [main] INFO com.torrenttunes.client.db.Actions - Applying libtorrent Settings...
    20:21:35.401 [main] INFO c.t.client.tools.DataSources - Operating system linux
    20:21:35.403 [main] INFO c.t.client.tools.DataSources - Using libtorrent @ /home/troll/.torrenttunes-client/src/lib/x86_64/libjlibtorrent.so
    Java HotSpot(TM) Server VM warning: You have loaded library /home/troll/.torrenttunes-client/src/lib/x86_64/libjlibtorrent.so which might have disabled stack guard. The VM will try to fix the stack guard now.
    It's highly recommended that you fix the library with 'execstack -c ', or link it with '-z noexecstack'.
    Exception in thread "main" java.lang.UnsatisfiedLinkError: Look for your architecture binary instructions at:    https://github.com/frostwire/frostwire-jlibtorrent
    at com.frostwire.jlibtorrent.swig.libtorrent_jni.(libtorrent_jni.java:22)
    at com.frostwire.jlibtorrent.swig.libtorrentConstants.(libtorrentConstants.java:12)
    at com.frostwire.jlibtorrent.LibTorrent.version(LibTorrent.java:16)
    at com.torrenttunes.client.LibtorrentEngine.(LibtorrentEngine.java:120)
    at com.torrenttunes.client.LibtorrentEngine.(LibtorrentEngine.java:96)
    at com.torrenttunes.client.db.Actions.updateLibtorrentSettings(Actions.java:122)
    at com.torrenttunes.client.Main.setupSettings(Main.java:95)
    at com.torrenttunes.client.Main.doMain(Main.java:71)
    at com.torrenttunes.client.Main.main(Main.java:128)
```

**Comment by gubatron** [comment]
don't they need to specify classpath & library path?

**Comment by tchoulihan** [comment]
It loads the library during runtime instead of using library.path, because then I know which library to use depending on the OS. This works on linux 64 bit/mac os x / windows 32 bit. 

I'd assumed that the `jlibtorrent-linux` `libjlibtorrent.so` was both x86 and x64 compatible, since its parent folder is named `x86_64`.

**Comment by aldenml** [comment]
That's the name for 64 bits (https://en.wikipedia.org/wiki/X86-64).

**Comment by tchoulihan** [comment]
Ah I'm dumb. Would it be possible to build a 32 bit version and release it under the `jlibtorrent-linux` artifact?

**Comment by aldenml** [comment]
Thinking about it, but since we don't test it, it's the same for the windows 64 bits. Not sure about it.

**Comment by tchoulihan** [comment]
No problem, just letting you guys know about some downstream requests.

**Comment by aldenml** [comment]
Released linux 32 bit version with 1.1.0.9

**Comment by gubatron** [comment]
Excellent news!

**Comment by tchoulihan** [comment]
Thanks! And for the 32 bit linux support too!
