### ISSUE TITLE
Error when creating new Session() with jlibtorrent 1.1.0.20

### ISSUE THREAD

**Issue by tchoulihan** [frostwire/frostwire-jlibtorrent#76]
Just updated jlibtorrent to version `1.1.0.20`( both `jlibtorrent` and `jlibtorrent-linux` maven deps) and I'm getting the following error when creating a `new Session()`

```java
java.lang.UnsatisfiedLinkError: com.frostwire.jlibtorrent.swig.libtorrent_jni.alert_picker_log_notification_get()I
	at com.frostwire.jlibtorrent.swig.libtorrent_jni.alert_picker_log_notification_get(Native Method)
	at com.frostwire.jlibtorrent.swig.alert$category_t.<clinit>(alert.java:518)
	at com.frostwire.jlibtorrent.Session.createSession(Session.java:1068)
	at com.frostwire.jlibtorrent.Session.<init>(Session.java:57)
	at com.frostwire.jlibtorrent.Session.<init>(Session.java:116)
	at com.torrenttunes.client.LibtorrentEngine.<init>(LibtorrentEngine.java:134)
	at com.torrenttunes.client.LibtorrentEngine.<clinit>(LibtorrentEngine.java:99)
	at com.torrenttunes.client.DerpTest.testDerp8(DerpTest.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```

**Comment by aldenml** [comment]
Can you update to 1.1.0.22? I can't provide support/help for older versions

**Comment by tchoulihan** [comment]
My apologies wasting your time here, you're correct it was a version issue, I hadn't loaded the correct `libjlibtorrent.so` file.
